### ISSUE TITLE
work around heroku 30 sec timout

### ISSUE THREAD

**Issue by riverscuomo** [riverscuomo/spotkin#32]
```
 at=info method=OPTIONS path="/process_job" host=spotkin-1b998975756a.herokuapp.com request_id=683d41ec-10dd-47b8-8708-f3fbea6ac7b3 fwd="101.174.38.50" dyno=web.1 connect=0ms service=4ms status=200 bytes=392 protocol=https
2024-08-21T22:23:26.678615+00:00 app[web.1]: 10.1.88.35 - - [21/Aug/2024:22:23:26 +0000] "OPTIONS /process_job HTTP/1.1" 200 0 "https://spotkin.web.app/" "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Mobile Safari/537.36"
2024-08-21T22:23:27.110104+00:00 app[web.1]: spotkin playlist {'name': 'Spotkin', 'playlist_id': '0VsRPfk2SjGo6dETwYp4UI', 'scheduled_time': 15, 'description': '', 'ban_skits': False, 'last_track_ids': [], 'banned_artists': [], 'banned_tracks': [], 'banned_genres': [], 'exceptions_to_banned_genres': [], 'recipe': [{'source_playlist_name': 'Drive Time', 'source_playlist_id': '0ilNnz4Yiq022Vk2DmIyUn', 'quantity': 4}, {'source_playlist_name': 'The Deluge Fanning Dempsey', 'source_playlist_id': '2jZ8kt4xRBYn2wMDkBAxKF', 'quantity': 4}, {'source_playlist_name': 'This Is Ash', 'source_playlist_id': '37i9dQZF1DZ06evO1gRNgV', 'quantity': 4}, {'source_playlist_name': 'Weezer', 'source_playlist_id': '637JXZYZ7uUzKN9RI0ol8C', 'quantity': 3}, {'source_playlist_name': 'Rivers', 'source_playlist_id': '3uKFPjYv29UMadfpP878Gr', 'quantity': 3}, {'source_playlist_name': 'Double J Best New Music', 'source_playlist_id': '3eVaP90RyWrOKu6Gejw5Eg', 'quantity': 3}, {'source_playlist_name': 'Discovery: The Best New Music', 'source_playlist_id': '4UWYHQZ83r0lhP530Qy2Il', 'quantity': 3}, {'source_playlist_name': 'Chicago The Musical', 'source_playlist_id': '11TNift0ZcjmQe50sB9HDL', 'quantity': 3}, {'source_playlist_name': 'Discoveries', 'source_playlist_id': '1OZ9XAKUGF3x5mgpizEGjF', 'quantity': 2}, {'source_playlist_name': 'Australian Indie Mix', 'source_playlist_id': '37i9dQZF1EIcLyY4fNNQaC', 'quantity': 2}, {'source_playlist_name': 'Top Songs - Australia', 'source_playlist_id': '37i9dQZEVXbK4fwx2r07XW', 'quantity': 2}, {'source_playlist_name': '60s Rock Anthems', 'source_playlist_id': '37i9dQZF1DWWzBc3TOlaAV', 'quantity': 1}, {'source_playlist_name': '90s/00s Australian Alternative', 'source_playlist_id': '3SblRaivH2XN7kouiD8M17', 'quantity': 1}, {'source_playlist_name': 'Primary Years 81-87', 'source_playlist_id': '4ZNKpV7mNW1MU1fCd5oDou', 'quantity': 1}, {'source_playlist_name': 'High School 88-92', 'source_playlist_id': '3xYMVF2dGd7EJGVYyoolWg', 'quantity': 1}, {'source_playlist_name': 'Uni, then some 93-99', 'source_playlist_id': '1asaBep9CBkkX642FUDL6W', 'quantity': 1}, {'source_playlist_name': 'Calm before the storm 00-06', 'source_playlist_id': '0jK5pfHTPMSKPCeD569kEG', 'quantity': 1}, {'source_playlist_name': "Best of British 60's", 'source_playlist_id': '6yIw0Ej6ewHGGMqaZpa6Wj', 'quantity': 1}, {'source_playlist_name': '1000 Greatest Songs Of All Time', 'source_playlist_id': '2LOxEzC4KmoWJ9NhW0kz5M', 'quantity': 1}, {'source_playlist_name': 'New Music Friday AU & NZ', 'source_playlist_id': '37i9dQZF1DWT2SPAYawYcO', 'quantity': 1}, {'source_playlist_name': '80s Hits', 'source_playlist_id': '37i9dQZF1DXb57FjYWz00c', 'quantity': 1}, {'source_playlist_name': 'Triple J Hottest 100 1993-2021', 'source_playlist_id': '1lUp5KkvBPTWYk6Sa5qNUO', 'quantity': 1}, {'source_playlist_name': 'Release Radar', 'source_playlist_id': '37i9dQZEVXbhu4KSaoGy07', 'quantity': 2}], 'min_popularity': None, 'max_popularity': None, 'min_duration': None, 'max_duration': None, 'min_danceability': None, 'max_danceability': None, 'min_energy': None, 'max_energy': None, 'min_acousticness': None, 'max_acousticness': None, 'index': 0}
2024-08-21T22:23:27.110366+00:00 app[web.1]: Getting tracks from the playlists earmarked for the Spotkin playlist...
2024-08-21T22:23:27.110394+00:00 app[web.1]: - sampling up to 4 Spotify tracks from the playlist 'Drive Time'... 
2024-08-21T22:23:32.425724+00:00 app[web.1]: - sampling up to 4 Spotify tracks from the playlist 'The Deluge Fanning Dempsey'... 
2024-08-21T22:23:32.537766+00:00 app[web.1]: - sampling up to 4 Spotify tracks from the playlist 'This Is Ash'... 
2024-08-21T22:23:32.957106+00:00 app[web.1]: - sampling up to 3 Spotify tracks from the playlist 'Weezer'... 
2024-08-21T22:23:34.722524+00:00 app[web.1]: - sampling up to 3 Spotify tracks from the playlist 'Rivers'... 
2024-08-21T22:23:34.959606+00:00 app[web.1]: - sampling up to 3 Spotify tracks from the playlist 'Double J Best New Music'... 
2024-08-21T22:23:36.323578+00:00 app[web.1]: - sampling up to 3 Spotify tracks from the playlist 'Discovery: The Best New Music'... 
2024-08-21T22:23:38.142501+00:00 app[web.1]: - sampling up to 3 Spotify tracks from the playlist 'Chicago The Musical'... 
2024-08-21T22:23:38.405061+00:00 app[web.1]: - sampling up to 2 Spotify tracks from the playlist 'Discoveries'... 
2024-08-21T22:23:38.721710+00:00 app[web.1]: - sampling up to 2 Spotify tracks from the playlist 'Australian Indie Mix'... 
2024-08-21T22:23:39.105634+00:00 app[web.1]: - sampling up to 2 Spotify tracks from the playlist 'Top Songs - Australia'... 
2024-08-21T22:23:39.521411+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist '60s Rock Anthems'... 
2024-08-21T22:23:40.162349+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist '90s/00s Australian Alternative'... 
2024-08-21T22:23:40.970371+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'Primary Years 81-87'... 
2024-08-21T22:23:41.814906+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'High School 88-92'... 
2024-08-21T22:23:42.633004+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'Uni, then some 93-99'... 
2024-08-21T22:23:43.251482+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'Calm before the storm 00-06'... 
2024-08-21T22:23:43.857320+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'Best of British 60's'... 
2024-08-21T22:23:44.991257+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist '1000 Greatest Songs Of All Time'... 
2024-08-21T22:23:50.079636+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'New Music Friday AU & NZ'... 
2024-08-21T22:23:50.722696+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist '80s Hits'... 
2024-08-21T22:23:51.474150+00:00 app[web.1]: - sampling up to 1 Spotify tracks from the playlist 'Triple J Hottest 100 1993-2021'... 
2024-08-21T22:23:57.049309+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/process_job" host=spotkin-1b998975756a.herokuapp.com request_id=90c914fe-c009-45f2-abd5-eb9f72aed649 fwd="101.174.38.50" dyno=web.1 connect=0ms service=30003ms status=503 bytes=0 protocol=https
2024-08-21T22:23:57.602830+00:00 app[web.1]: [2024-08-21 22:23:57 +0000] [2] [CRITICAL] WORKER TIMEOUT (pid:9)
2024-08-21T22:23:57.606510+00:00 app[web.1]: [2024-08-21 22:23:57 +0000] [9] [ERROR] Error handling request /process_job
2024-08-21T22:23:57.606511+00:00 app[web.1]: Traceback (most recent call last):
2024-08-21T22:23:57.606511+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 135, in handle
2024-08-21T22:23:57.606512+00:00 app[web.1]:     self.handle_request(listener, req, client, addr)
2024-08-21T22:23:57.606512+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/sync.py", line 178, in handle_request
2024-08-21T22:23:57.606512+00:00 app[web.1]:     respiter = self.wsgi(environ, resp.start_response)
2024-08-21T22:23:57.606512+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606513+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/flask/app.py", line 1498, in __call__
2024-08-21T22:23:57.606513+00:00 app[web.1]:     return self.wsgi_app(environ, start_response)
2024-08-21T22:23:57.606514+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606514+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/flask/app.py", line 1473, in wsgi_app
2024-08-21T22:23:57.606514+00:00 app[web.1]:     response = self.full_dispatch_request()
2024-08-21T22:23:57.606514+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606515+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/flask/app.py", line 880, in full_dispatch_request
2024-08-21T22:23:57.606515+00:00 app[web.1]:     rv = self.dispatch_request()
2024-08-21T22:23:57.606515+00:00 app[web.1]:          ^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606515+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/flask/app.py", line 865, in dispatch_request
2024-08-21T22:23:57.606515+00:00 app[web.1]:     return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
2024-08-21T22:23:57.606516+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606516+00:00 app[web.1]:   File "/app/routes.py", line 8, in process_job_api
2024-08-21T22:23:57.606516+00:00 app[web.1]:     return job_service.process_job(request)
2024-08-21T22:23:57.606516+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606516+00:00 app[web.1]:   File "/app/job_service.py", line 64, in process_job
2024-08-21T22:23:57.606516+00:00 app[web.1]:     result = process_job(spotify, job)
2024-08-21T22:23:57.606517+00:00 app[web.1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606517+00:00 app[web.1]:   File "/app/spotkin/scripts/process_job.py", line 24, in process_job
2024-08-21T22:23:57.606517+00:00 app[web.1]:     tracks = get_all_tracks(job, spotify)
2024-08-21T22:23:57.606517+00:00 app[web.1]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606517+00:00 app[web.1]:   File "/app/spotkin/scripts/get_all_tracks.py", line 43, in get_all_tracks
2024-08-21T22:23:57.606517+00:00 app[web.1]:     new_tracks = sample_playlist_tracks(
2024-08-21T22:23:57.606518+00:00 app[web.1]:                  ^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606518+00:00 app[web.1]:   File "/app/spotkin/scripts/api.py", line 65, in sample_playlist_tracks
2024-08-21T22:23:57.606518+00:00 app[web.1]:     all_tracks = get_playlist_tracks(spotify, playlist_id)
2024-08-21T22:23:57.606518+00:00 app[web.1]:                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606518+00:00 app[web.1]:   File "/app/spotkin/scripts/api.py", line 79, in get_playlist_tracks
2024-08-21T22:23:57.606518+00:00 app[web.1]:     results = spotify.next(results)
2024-08-21T22:23:57.606519+00:00 app[web.1]:               ^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/spotipy/client.py", line 351, in next
2024-08-21T22:23:57.606519+00:00 app[web.1]:     return self._get(result["next"])
2024-08-21T22:23:57.606519+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606519+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/spotipy/client.py", line 327, in _get
2024-08-21T22:23:57.606519+00:00 app[web.1]:     return self._internal_call("GET", url, payload, kwargs)
2024-08-21T22:23:57.606519+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/spotipy/client.py", line 270, in _internal_call
2024-08-21T22:23:57.606520+00:00 app[web.1]:     response = self._session.request(
2024-08-21T22:23:57.606520+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
2024-08-21T22:23:57.606520+00:00 app[web.1]:     resp = self.send(prep, **send_kwargs)
2024-08-21T22:23:57.606520+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606520+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
2024-08-21T22:23:57.606521+00:00 app[web.1]:     r = adapter.send(request, **kwargs)
2024-08-21T22:23:57.606521+00:00 app[web.1]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606521+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
2024-08-21T22:23:57.606521+00:00 app[web.1]:     resp = conn.urlopen(
2024-08-21T22:23:57.606522+00:00 app[web.1]:            ^^^^^^^^^^^^^
2024-08-21T22:23:57.606522+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/connectionpool.py", line 789, in urlopen
2024-08-21T22:23:57.606522+00:00 app[web.1]:     response = self._make_request(
2024-08-21T22:23:57.606522+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606522+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/connectionpool.py", line 536, in _make_request
2024-08-21T22:23:57.606522+00:00 app[web.1]:     response = conn.getresponse()
2024-08-21T22:23:57.606523+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606523+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/urllib3/connection.py", line 464, in getresponse
2024-08-21T22:23:57.606523+00:00 app[web.1]:     httplib_response = super().getresponse()
2024-08-21T22:23:57.606523+00:00 app[web.1]:                        ^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606523+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/http/client.py", line 1428, in getresponse
2024-08-21T22:23:57.606524+00:00 app[web.1]:     response.begin()
2024-08-21T22:23:57.606524+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/http/client.py", line 331, in begin
2024-08-21T22:23:57.606526+00:00 app[web.1]:     version, status, reason = self._read_status()
2024-08-21T22:23:57.606526+00:00 app[web.1]:                               ^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606526+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/http/client.py", line 292, in _read_status
2024-08-21T22:23:57.606527+00:00 app[web.1]:     line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
2024-08-21T22:23:57.606527+00:00 app[web.1]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/socket.py", line 708, in readinto
2024-08-21T22:23:57.606527+00:00 app[web.1]:     return self._sock.recv_into(b)
2024-08-21T22:23:57.606527+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606527+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/ssl.py", line 1252, in recv_into
2024-08-21T22:23:57.606527+00:00 app[web.1]:     return self.read(nbytes, buffer)
2024-08-21T22:23:57.606528+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606528+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/ssl.py", line 1104, in read
2024-08-21T22:23:57.606528+00:00 app[web.1]:     return self._sslobj.read(len, buffer)
2024-08-21T22:23:57.606528+00:00 app[web.1]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024-08-21T22:23:57.606528+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.12/site-packages/gunicorn/workers/base.py", line 203, in handle_abort
2024-08-21T22:23:57.606528+00:00 app[web.1]:     sys.exit(1)
2024-08-21T22:23:57.606528+00:00 app[web.1]: SystemExit: 1

**Comment by riverscuomo** [comment]
I think I sped this up a lot so it shouldn't fail?
